M48
; DRILL file {KiCad 7.0.7} date Mon Feb 26 19:43:46 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-26T19:43:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X3.7356Y-5.1166
X3.9631Y-5.1166
T2
X4.2657Y-3.3406
X4.2657Y-5.2303
X5.565Y-3.3406
X5.565Y-5.2303
T0
M30
